-- ====================================================================================================
-- Enterprise Schema Migration Script: V1__init_roles_and_users.sql
-- Target Service: User Service (membership-hub)
-- Architecture Baseline: Quarkus 3.15.x / PostgreSQL 15+
--
-- Traceability Tags:
-- [DAT-001] Database Schema Definition for System Roles and User Accounts
-- [DAT-002] Relational Constraints, Indexing, and RBAC Seed Metadata
-- ====================================================================================================

-- ----------------------------------------------------------------------------------------------------
-- 1. ROLES TABLE DEFINITION [DAT-001]
-- Purpose: Defines the 5-tier Role-Based Access Control (RBAC) authorization matrix.
-- Constraint: Uses ANSI SQL standard types (SMALLINT, VARCHAR) without proprietary ENUMs for portability.
-- ----------------------------------------------------------------------------------------------------
CREATE TABLE roles (
    -- [DAT-001] Primary Key: Identifier for RBAC role level (1: SystemAdmin, 2: CenterAdmin, etc.)
    role_id SMALLINT NOT NULL,

    -- [DAT-001] Role Name: Unique immutable system descriptor for role matching in security filters
    name VARCHAR(30) NOT NULL,

    -- [DAT-001] Description: Human-readable narrative describing permission boundaries
    description VARCHAR(200),

    -- [DAT-001] Primary Key Constraint: Enforces uniqueness and primary identity indexing
    CONSTRAINT pk_roles PRIMARY KEY (role_id),

    -- [DAT-001] Unique Constraint: Prevents duplicate role naming within authorization domain
    CONSTRAINT uq_roles_name UNIQUE (name)
);

-- Descriptive comment metadata on table and columns for audit traceability
COMMENT ON TABLE roles IS 'Stores system-wide RBAC role definitions and metadata [DAT-001]';
COMMENT ON COLUMN roles.role_id IS 'Unique identifier for the RBAC role [DAT-001]';
COMMENT ON COLUMN roles.name IS 'System identity token for authorization checks (e.g., SystemAdmin) [DAT-001]';
COMMENT ON COLUMN roles.description IS 'Operational description of role capabilities and restrictions [DAT-001]';

-- ----------------------------------------------------------------------------------------------------
-- 2. USERS TABLE DEFINITION [DAT-001]
-- Purpose: Primary identity ledger storing credential hashes, profile data, and auth provider states.
-- Security: Stores passwords as 60-character BCrypt hashes. Supports OAuth2 social federations.
-- ----------------------------------------------------------------------------------------------------
CREATE TABLE users (
    -- [DAT-001] Primary Key: Cryptographically random UUID v4 identifier generated by database engine
    user_id UUID DEFAULT gen_random_uuid() NOT NULL,

    -- [DAT-001] User Email: RFC 5322 compliant unique email address acting as primary authentication identity
    email VARCHAR(255) NOT NULL,

    -- [DAT-001] Password Hash: Fixed-length 60-character container for OWASP-compliant BCrypt hashed credentials
    password_hash CHAR(60) NOT NULL,

    -- [DAT-001] Full Name: UTF-8 compatible personal identifier for user interfaces and certificates
    full_name VARCHAR(100) NOT NULL,

    -- [DAT-001] Role Reference: Foreign key linking to roles table enforcing valid RBAC role assignment
    role_id SMALLINT NOT NULL,

    -- [DAT-001] Auth Provider: Authentication realm (local credentials or federated OAuth2 providers)
    provider VARCHAR(20) DEFAULT 'local' NOT NULL,

    -- [DAT-001] Audit Timestamp: Creation timestamp recorded at database insertion time
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- [DAT-001] Audit Timestamp: Last modification timestamp maintained by application/trigger lifecycle
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- [DAT-001] Primary Key Constraint
    CONSTRAINT pk_users PRIMARY KEY (user_id),

    -- [DAT-001] Unique Constraint on Email: Blocks duplicate registrations at the database storage engine layer
    CONSTRAINT uq_users_email UNIQUE (email),

    -- [DAT-001] Foreign Key Constraint: Guarantees referential integrity between users and roles
    CONSTRAINT fk_users_role FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    -- [DAT-001] Check Constraint: Enforces strict whitelist of supported identity providers (anti-injection rail)
    CONSTRAINT chk_users_provider CHECK (provider IN ('local', 'firebase', 'google', 'facebook'))
);

-- Descriptive comment metadata on users table
COMMENT ON TABLE users IS 'Master authentication and profile ledger for user accounts [DAT-001]';
COMMENT ON COLUMN users.user_id IS 'Unique UUID identifier for the user entity [DAT-001]';
COMMENT ON COLUMN users.email IS 'Unique validated email address for login and notifications [DAT-001]';
COMMENT ON COLUMN users.password_hash IS 'BCrypt password hash with cost factor >= 10 (CHAR(60)) [DAT-001]';
COMMENT ON COLUMN users.full_name IS 'Full legal or display name of the user [DAT-001]';
COMMENT ON COLUMN users.role_id IS 'Foreign key reference to roles.role_id [DAT-001]';
COMMENT ON COLUMN users.provider IS 'Identity provider token: local, firebase, google, facebook [DAT-001]';
COMMENT ON COLUMN users.created_at IS 'Immutable UTC timestamp of record creation [DAT-001]';
COMMENT ON COLUMN users.updated_at IS 'UTC timestamp of the most recent profile update [DAT-001]';

-- ----------------------------------------------------------------------------------------------------
-- 3. INDEX OPTIMIZATION RAIL [DAT-002]
-- Purpose: Delivers sub-second query performance (< 200ms) for auth lookups and role-filtered queries.
-- ----------------------------------------------------------------------------------------------------

-- [DAT-002] Index on email for rapid user credential lookups during authentication workflow (B-Tree)
CREATE INDEX idx_users_email ON users (email);

-- [DAT-002] Index on role_id to optimize RBAC authorization checks, join traversals, and administrative lists
CREATE INDEX idx_users_role_id ON users (role_id);

-- ----------------------------------------------------------------------------------------------------
-- 4. RBAC SEED DATA INGESTION [DAT-002]
-- Purpose: Pre-populates deterministic reference data for 5 system authorization tiers.
-- ----------------------------------------------------------------------------------------------------
INSERT INTO roles (role_id, name, description) VALUES
    (1, 'SystemAdmin', 'Quản trị viên hệ thống toàn cục - Toàn quyền cấu hình và giám sát hệ thống'),
    (2, 'CenterAdmin', 'Quản trị viên cấp trung tâm - Quản lý nhân sự, khóa học và học viên tại trung tâm'),
    (3, 'Manager', 'Quản lý cấp dưới - Hỗ trợ vận hành và điều phối lịch học tại trung tâm'),
    (4, 'Teacher', 'Giáo viên - Xem lịch giảng dạy, danh sách lớp học và quản lý điểm danh'),
    (5, 'Student', 'Học viên - Đăng ký khóa học, quét QR điểm danh và theo dõi thẻ thành viên');