/**
 * AuthController.java
 *
 * This controller implements the core authentication and user registration APIs for the
 * membership-hub project. It provides endpoints for user registration, login, and fetching
 * the currently authenticated user's details. All operations enforce idempotency, rigorous
 * input validation, comprehensive logging, and structured error handling with full cause
 * chain preservation.
 *
 * Traceability Tags:
 *   [REQ-001] – User registration API contract and behavior.
 *   [REQ-002] – User login API contract and behavior.
 *   [ARC-001] – JWT token generation and validation logic.
 *   [ARC-002] – Password hashing and verification mechanisms.
 *   [ARC-003] – Idempotency key enforcement for mutation operations.
 *   [ARC-004] – Structured logging and audit trail requirements.
 *   [ARC-005] – Secure exception handling and cause chain preservation.
 *   [DAT-001] – Users table schema and data model.
 *   [DAT-002] – Roles table schema and data model.
 *   [NFR-001] – OWASP SQL Injection prevention via prepared statements.
 *   [NFR-002] – OWASP XSS mitigation through output encoding.
 *   [NFR-003] – JWT token expiration and refresh token handling.
 *   [NFR-004] – Rate limiting and throttling considerations.
 *   [NFR-005] – Comprehensive audit logging and traceability.
 *   [NFR-006] – Secure password storage (bcrypt).
 *   [NFR-007] – Multi‑tenant isolation and header‑based tenant identification.
 *   [NFR-008] – Zero‑trust network segmentation and private VPC usage.
 *   [NFR-009] – End‑to‑end encryption and secure channel enforcement.
 */
package org.nlh4j.saas.membership-hub.auth;

import jakarta.inject.Inject;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.*;
import jakarta.ws.rs.core.Response.Status;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import org.jboss.resteasy.reactive.RestResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Custom JAX‑RS exception for registration failures.
 * The original cause is preserved to satisfy the enterprise exception‑cause chain law.
 */
@Path("/api/auth")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class AuthController {

    /* -------------------------------------------------------------------------
       Enterprise‑wide Constants – hoisted to the class crown per Anti‑Magic‑Numbers policy
       ------------------------------------------------------------------------- */
    private static final Logger logger = LoggerFactory.getLogger(AuthController.class);

    /* Traceability tags – required for audit compliance */
    // [REQ-001], [REQ-002], [ARC-001]‑[ARC-005], [DAT-001], [DAT-002], [NFR-001]‑[NFR-009]

    /** Success message for user registration. */
    public static final String REGISTRATION_SUCCESS_MSG = "User registered successfully";

    /** Success message for user login. */
    public static final String LOGIN_SUCCESS_MSG = "User logged in successfully";

    /** JWT token type prefix. */
    public static final String TOKEN_TYPE = "Bearer";

    /** Access token validity window – 15 minutes (milliseconds). */
    public static final long JWT_EXPIRATION_MS = 15 * 60 * 1000L;

    /** Refresh token validity window – 7 days (milliseconds). */
    public static final long REFRESH_TOKEN_EXPIRATION_MS = 7L * 24 * 60 * 60 * 1000L;

    /** HTTP header name for idempotency key enforcement. */
    public static final String IDEMPOTENCY_HEADER = "X-Idempotency-Key";

    /** Minimum password length per policy. */
    public static final int MIN_PASSWORD_LENGTH = 8;

    /** Supported OAuth providers. */
    public static final String[] SUPPORTED_PROVIDERS = {"local", "google", "facebook", "firebase"};

    /* -------------------------------------------------------------------------
       Injected dependencies – service layer for business logic
       ------------------------------------------------------------------------- */
    @Inject
    AuthService authService;

    /* -------------------------------------------------------------------------
       Request / Response DTOs – kept inside the controller for compactness.
       ------------------------------------------------------------------------- */

    /** DTO for user registration requests. */
    public static class UserRegistrationRequest {
        @NotBlank(message = "Email is required")
        private String email;
        @NotBlank(message = "Password is required")
        private String password;
        @NotBlank(message = "Full name is required")
        private String fullName;
        private String provider = "local"; // default provider

        // Getters / Setters (omitted for brevity – generated by IDE / Lombok in real code)
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public String getPassword() { return password; }
        public void setPassword(String password) { this.password = password; }
        public String getFullName() { return fullName; }
        public void setFullName(String fullName) { this.fullName = fullName; }
        public String getProvider() { return provider; }
        public void setProvider(String provider) { this.provider = provider; }
    }

    /** DTO for user login requests. */
    public static class UserLoginRequest {
        @NotBlank(message = "Email is required")
        private String email;
        @NotBlank(message = "Password is required")
        private String password;

        // Getters / Setters
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public String getPassword() { return password; }
        public void setPassword(String password) { this.password = password; }
    }

    /** DTO returned after successful authentication. */
    public static class UserDto {
        private UUID userId;
        private String email;
        private String fullName;
        private short roleId;
        private String provider;
        private Instant createdAt;

        // Getters / Setters
        public UUID getUserId() { return userId; }
        public void setUserId(UUID userId) { this.userId = userId; }
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public String getFullName() { return fullName; }
        public void setFullName(String fullName) { this.fullName = fullName; }
        public short getRoleId() { return roleId; }
        public void setRoleId(short roleId) { this.roleId = roleId; }
        public String getProvider() { return provider; }
        public void setProvider(String provider) { this.provider = provider; }
        public Instant getCreatedAt() { return createdAt; }
        public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
    }

    /** DTO encapsulating JWT tokens. */
    public static class AuthToken {
        private String accessToken;
        private String refreshToken;
        private long expiresIn;

        // Getters / Setters
        public String getAccessToken() { return accessToken; }
        public void setAccessToken(String accessToken) { this.accessToken = accessToken; }
        public String getRefreshToken() { return refreshToken; }
        public void setRefreshToken(String refreshToken) { this.refreshToken = refreshToken; }
        public long getExpiresIn() { return expiresIn; }
        public void setExpiresIn(long expiresIn) { this.expiresIn = expiresIn; }
    }

    /* -------------------------------------------------------------------------
       Custom JAX‑RS exceptions – preserve original cause per enterprise policy
       ------------------------------------------------------------------------- */
    @Provider
    public static class RegistrationException extends WebApplicationException {
        public RegistrationException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    @Provider
    public static class LoginException extends WebApplicationException {
        public LoginException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    @Provider
    public static class AuthenticationException extends WebApplicationException {
        public AuthenticationException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    /* -------------------------------------------------------------------------
       Registration endpoint – POST /api/auth/register
       ------------------------------------------------------------------------- */
    @POST
    @Path("/register")
    public RestResponse<?> register(
            @HeaderParam(IDEMPOTENCY_HEADER) String idempotencyKey,
            @Valid UserRegistrationRequest request) {

        // Entry‑point logging per NFR‑005
        logger.info("[ENTRY] [REQ-001] Processing user registration for email: {}", request.getEmail());

        try {
            // Idempotency validation – ARC‑003
            if (idempotencyKey == null || idempotencyKey.isBlank()) {
                logger.warn("[VALIDATION] [REQ-001] Missing idempotency key for registration");
                return RestResponse.status(Status.BAD_REQUEST)
                        .entity(Map.of("error", "Idempotency key required"))
                        .build();
            }

            // Delegate to service layer (contains prepared‑statement based persistence)
            UserDto user = authService.register(request);

            logger.info("[EXIT] [REQ-001] Registration completed for userId: {}", user.getUserId());
            return RestResponse.ok(Map.of("message", REGISTRATION_SUCCESS_MSG, "user", user));

        } catch (Exception e) {
            // Comprehensive error logging – ARC‑004, includes traceability tag
            logger.error("[CRITICAL FAIL] [ARC-005] Registration failed for email: {}. Raw error: {}",
                    request.getEmail(), e.getMessage(), e);
            // Preserve cause chain – ARC‑005
            throw new RegistrationException("Registration processing error", e);
        }
    }

    /* -------------------------------------------------------------------------
       Login endpoint – POST /api/auth/login
       ------------------------------------------------------------------------- */
    @POST
    @Path("/login")
    public RestResponse<?> login(
            @HeaderParam(IDEMPOTENCY_HEADER) String idempotencyKey,
            @Valid UserLoginRequest request) {

        logger.info("[ENTRY] [REQ-002] Processing login for email: {}", request.getEmail());

        try {
            if (idempotencyKey == null || idempotencyKey.isBlank()) {
                logger.warn("[VALIDATION] [REQ-002] Missing idempotency key for login");
                return RestResponse.status(Status.BAD_REQUEST)
                        .entity(Map.of("error", "Idempotency key required"))
                        .build();
            }

            AuthToken token = authService.login(request);

            logger.info("[EXIT] [REQ-002] Login successful for email: {}", request.getEmail());
            return RestResponse.ok(Map.of("message", LOGIN_SUCCESS_MSG, "token", token));

        } catch (Exception e) {
            logger.error("[CRITICAL FAIL] [ARC-001] Login failed for email: {}. Raw error: {}",
                    request.getEmail(), e.getMessage(), e);
            throw new LoginException("Login processing error", e);
        }
    }

    /* -------------------------------------------------------------------------
       Get current user – GET /api/auth/me
       ------------------------------------------------------------------------- */
    @GET
    @Path("/me")
    public RestResponse<?> getCurrentUser(@HeaderParam("Authorization") String authHeader) {
        logger.info("[ENTRY] [REQ-001] Fetching current user info");

        try {
            if (authHeader == null || !authHeader.startsWith(TOKEN_TYPE + " ")) {
                logger.warn("[VALIDATION] [REQ-001] Missing or invalid Authorization header");
                return RestResponse.status(Status.UNAUTHORIZED)
                        .entity(Map.of("error", "Invalid authorization token"))
                        .build();
            }

            String token = authHeader.substring(TOKEN_TYPE.length()).trim();
            UserDto user = authService.getCurrentUser(token);

            logger.info("[EXIT] [REQ-001] Current user fetched for userId: {}", user.getUserId());
            return RestResponse.ok(user);

        } catch (Exception e) {
            logger.error("[CRITICAL FAIL] [ARC-002] Fetch current user failed. Raw error: {}",
                    e.getMessage(), e);
            throw new AuthenticationException("Failed to retrieve user", e);
        }
    }
}