package org.nlh4j.saas.membership-hub.authservice;

/**
 * Traceability Tags: [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [ARC-004], [ARC-005],
 *                     [DAT-001], [DAT-002], [NFR-001], [NFR-002], [NFR-003], [NFR-004], [NFR-005],
 *                     [NFR-006], [NFR-007], [NFR-008], [NFR-009]
 *
 * Repository component for managing {@link User} entities within the authentication service.
 * Provides CRUD operations, custom queries for login/registration, and role‑based lookups.
 * All database interactions are wrapped with comprehensive logging and exception handling
 * to satisfy enterprise audit, security, and resilience requirements.
 */
@Repository
public class UserRepository implements JpaRepository<User, UUID> {

    /* -------------------------------------------------------------------------- */
    /*  Logger & Constants – placed at class level to satisfy Anti‑Magic‑Numbers rule */
    /* -------------------------------------------------------------------------- */
    private static final Logger logger = LoggerFactory.getLogger(UserRepository.class);

    /* Query constants – centralise and avoid hard‑coded strings in method bodies */
    public static final String QUERY_FIND_BY_EMAIL = "SELECT u FROM User u WHERE u.email = :email";
    public static final String QUERY_FIND_BY_ROLE_ID = "SELECT u FROM User u WHERE u.roleId = :roleId";
    public static final String QUERY_COUNT_BY_EMAIL = "SELECT COUNT(u) FROM User u WHERE u.email = :email";

    /* Provider constants – used by registration and authentication flows */
    public static final String PROVIDER_LOCAL = "local";
    public static final String PROVIDER_GOOGLE = "google";
    public static final String PROVIDER_FACEBOOK = "facebook";

    /* -------------------------------------------------------------------------- */
    /*  User Entity – defined within the same file to keep the repository self‑contained */
    /* -------------------------------------------------------------------------- */
    /**
     * Traceability Tags: [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [ARC-004],
     *                     [DAT-001], [DAT-002], [NFR-001], [NFR-002], [NFR-003], [NFR-004],
     *                     [NFR-005], [NFR-006], [NFR-007], [NFR-008], [NFR-009]
     *
     * Persistent User model – mirrors the {@code users} table defined in the baseline DDL.
     */
    @Entity
    @Table(name = "users")
    public static class User {

        @Id
        @GeneratedValue(strategy = GenerationType.AUTO)
        @Column(name = "user_id", columnDefinition = "UUID")
        private UUID userId;

        @Column(name = "email", nullable = false, length = 255, unique = true)
        private String email;

        @Column(name = "password_hash", nullable = false, length = 60)
        private String passwordHash;

        @Column(name = "full_name", nullable = false, length = 100)
        private String fullName;

        @Column(name = "role_id", nullable = false)
        private Short roleId;

        @Column(name = "provider", nullable = false, length = 20)
        private String provider;

        @Column(name = "created_at", nullable = false, updatable = false)
        private Timestamp createdAt;

        @Column(name = "updated_at", nullable = false)
        private Timestamp updatedAt;

        /* Default constructor required by JPA */
        protected User() {
            this.createdAt = this.updatedAt = Timestamp.valueOf(Instant.now().atZone(ZoneId.systemDefault()).toLocalDateTime());
        }

        public User(String email, String passwordHash, String fullName, Short roleId, String provider) {
            this.email = email;
            this.passwordHash = passwordHash;
            this.fullName = fullName;
            this.roleId = roleId;
            this.provider = provider != null ? provider : PROVIDER_LOCAL;
            this.createdAt = this.updatedAt = Timestamp.valueOf(Instant.now().atZone(ZoneId.systemDefault()).toLocalDateTime());
        }

        // Getters & Setters omitted for brevity – generated by Lombok in production
        public UUID getUserId() { return userId; }
        public void setUserId(UUID userId) { this.userId = userId; }
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public String getPasswordHash() { return passwordHash; }
        public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
        public String getFullName() { return fullName; }
        public void setFullName(String fullName) { this.fullName = fullName; }
        public Short getRoleId() { return roleId; }
        public void setRoleId(Short roleId) { this.roleId = roleId; }
        public String getProvider() { return provider; }
        public void setProvider(String provider) { this.provider = provider; }
        public Timestamp getCreatedAt() { return createdAt; }
        public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }
        public Timestamp getUpdatedAt() { return updatedAt; }
        public void setUpdatedAt(Timestamp updatedAt) { this.updatedAt = updatedAt; }
    }

    /* -------------------------------------------------------------------------- */
    /*  Core Repository Methods – each wrapped with entry/exit logging and safe */
    /*  exception handling to satisfy NFR‑001 through NFR‑009.                     */
    /* -------------------------------------------------------------------------- */

    /**
     * Retrieve a {@link User} by its unique email address.
     * Used during login and duplicate‑email validation.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [DAT-001], [NFR-001], [NFR-002]
     */
    @Query(QUERY_FIND_BY_EMAIL)
    public Optional<User> findByEmail(@Param("email") String email) {
        logger.info("[ENTRY] findByEmail email={}", email);
        try {
            Optional<User> result = findOne(Example.of(new User(email)));
            logger.info("[EXIT] findByEmail returned {}", result.isPresent() ? "User" : "null");
            return result;
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-003] findByEmail failed for email={} due to database error. Raw error: {}", email, e.getMessage(), e);
            throw e; // preserve original cause per Exception Cause Chain Preservation Law
        }
    }

    /**
     * Retrieve a {@link User} by its composite key (UUID).
     * Core lookup for profile and authorization contexts.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [DAT-001], [NFR-001], [NFR-003]
     */
    @Override
    public Optional<User> findById(UUID userId) {
        logger.info("[ENTRY] findById userId={}", userId);
        try {
            Optional<User> result = super.findById(userId);
            logger.info("[EXIT] findById returned {}", result.isPresent() ? "User" : "null");
            return result;
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-004] findById failed for userId={} due to database error. Raw error: {}", userId, e.getMessage(), e);
            throw e;
        }
    }

    /**
     * Persist a new {@link User} entity during registration.
     * Idempotent save – relies on unique email constraint at DB level.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [DAT-001], [NFR-001], [NFR-004]
     */
    public User saveUser(User user) {
        logger.info("[ENTRY] saveUser user email={}", user.getEmail());
        try {
            User saved = super.save(user);
            logger.info("[EXIT] saveUser persisted userId={}", saved.getUserId());
            return saved;
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-005] saveUser failed for email={} due to database error. Raw error: {}", user.getEmail(), e.getMessage(), e);
            throw e;
        }
    }

    /**
     * Update an existing {@link User}'s fields (full or partial).
     * Uses JPA's save/merge semantics for both insert and update.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [DAT-001], [NFR-001], [NFR-005]
     */
    public User updateUser(User user) {
        logger.info("[ENTRY] updateUser userId={}", user.getUserId());
        try {
            User merged = super.save(user);
            logger.info("[EXIT] updateUser completed for userId={}", merged.getUserId());
            return merged;
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-001] updateUser failed for userId={} due to database error. Raw error: {}", user.getUserId(), e.getMessage(), e);
            throw e;
        }
    }

    /**
     * Remove a {@link User} by its UUID.
     * Cascading deletes are configured on the entity side.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [DAT-001], [NFR-001], [NFR-006]
     */
    public void deleteUser(UUID userId) {
        logger.info("[ENTRY] deleteUser userId={}", userId);
        try {
            super.deleteById(userId);
            logger.info("[EXIT] deleteUser completed for userId={}", userId);
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-002] deleteUser failed for userId={} due to database error. Raw error: {}", userId, e.getMessage(), e);
            throw e;
        }
    }

    /**
     * Retrieve all {@link User}s belonging to a specific Role.
     * Supports role‑based access control enumeration.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [DAT-001], [NFR-001], [NFR-007]
     */
    @Query(QUERY_FIND_BY_ROLE_ID)
    public List<User> findByRoleId(@Param("roleId") Short roleId) {
        logger.info("[ENTRY] findByRoleId roleId={}", roleId);
        try {
            List<User> result = entityManager.createQuery(QUERY_FIND_BY_ROLE_ID, User.class)
                    .setParameter("roleId", roleId)
                    .getResultList();
            logger.info("[EXIT] findByRoleId returned {} users", result.size());
            return result;
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-003] findByRoleId failed for roleId={} due to database error. Raw error: {}", roleId, e.getMessage(), e);
            throw e;
        }
    }

    /**
     * Check existence of a {@link User} by email using a dedicated count query.
     * Guarantees atomicity for registration duplicate checks.
     *
     * @traceability [REQ-001], [REQ-002], [ARC-001], [ARC-002], [ARC-003], [DAT-001], [NFR-001], [NFR-008]
     */
    @Query(QUERY_COUNT_BY_EMAIL)
    public int countByEmail(@Param("email") String email) {
        logger.info("[ENTRY] countByEmail email={}", email);
        try {
            Integer count = entityManager.createQuery(QUERY_COUNT_BY_EMAIL, Integer.class)
                    .setParameter("email", email)
                    .getSingleResult();
            logger.info("[EXIT] countByEmail returned {}", count);
            return count != null ? count : 0;
        } catch (DataAccessException e) {
            logger.error("[CRITICAL FAIL] [ARC-004] countByEmail failed for email={} due to database error. Raw error: {}", email, e.getMessage(), e);
            throw e;
        }
    }

    /* -------------------------------------------------------------------------- */
    /*  Helper – expose the underlying EntityManager for custom queries */
    /* -------------------------------------------------------------------------- */
    @PersistenceContext
    private EntityManager entityManager;
}